Added a feature that throws an error when a user enters an unsupported command.
RinkiyaKeDad/dependency-analyzer-poc pull request #53
Opened 2021-08-16 11:08 UTC by Lakshya8066

2021-08-19 11:04 UTC, Atharva-Shinde requested changes
Change the typo in error message - "argumant" to "argument"
 And add "an" before "input" in 'This command does not take any argumant as input.'

2021-08-20 07:21 UTC, RinkiyaKeDad requested changes, later dismissed
Thanks for the PR! Just one minor nit and we should be good to go :)

2021-08-20 07:21 UTC, RinkiyaKeDad commented on cmd/list.go
> +			return errors.New("Invalid input! This command does not take any argumant as input.")
I think we should go with `fmt.Errorf` because then we won't need to import another package here. Also please see #38 (comment)

2021-08-26 11:21 UTC, RinkiyaKeDad commented on cmd/list.go
> +			return fmt.Errorf("list does not take any argument as input")
`"list does not take any arguments"` for consistency 🙂

2021-08-26 14:39 UTC, lakshya8066 commented on cmd/list.go
> +			return fmt.Errorf("list does not take any argument as input")
oops, updating...

2021-08-27 05:47 UTC, RinkiyaKeDad commented
/label tide/merge-method-squash

2021-08-27 05:48 UTC, RinkiyaKeDad commented
Thanks!

/lgtm
/approve
/woof

2021-08-27 05:49 UTC, merged